server:
  port: ${port:8099}      # 直接运行的默认端口是8099.但是可以动态传参端口号

spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://192.168.81.130:3306/wangguo-red-book-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&&serverTimezone=UTC
    username: root
    password: Wg2034110399.
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  redis:
    host: 192.168.81.130
    port: 6379
    database: 0
    password: 12345678
  data:
    mongodb:
      uri: mongodb://root:12345678@192.168.81.140:27017
      database: wangguo-douyin
  rabbitmq:
    host: 192.168.81.140
    port: 5672
    username: wangguo
    password: 12345678
    virtual-host: wangguo-idouyin
  jackson:
    time-zone: GMT+8

  #  application:
#    name: wangguo-idouyin-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.81.130:8848 # nacos所在地址
# 打开监控
management:
  endpoint:
    web:
      exposure:
        include: '*'
# minio配置
minio: # 注意是小写
  endpoint: http://192.168.81.130:9000 # MinIO服务地址
  fileHost: http://192.168.81.130:9000 # 文件地址host
  bucketName: idouyin # 存储桶bucket名称
  accessKey: ROOT # 用户名
  secretKey: 12345678 # 密码
  imgSize:   # 图片大小限制，单位：m
  fileSize: # 文件大小限制，单位：m
